[package]
name = "ObsidianVault"
version = "1.0.0"
authors = ["Jimmy Briggs <jimmy.briggs@jimbrig.com"]
edition = "2023"
license = "MIT"
readme = "README.md"
repository = "https://github.com/jimbrig/JimsObsidianVault"
documentation = "https://publish.obsidian.md/jimsvault-published/"
description = """
Obsidian Knowledge as a Service Vault
"""
categories = ["obsidian", "knowledge", "vault", "publishing"]
keywords = ["obsidian", "knowledge", "vault", "publishing"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
obsidian-export = "22.1.0"

[dev-dependencies]
obsidian-export = "22.1.0"
