name: PSScriptAnalyzer
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: lint
        uses: devblackops/github-action-psscriptanalyzer@master
        with:
          sendComment: true
          failOnErrors: true
          failOnWarnings: true
          failOnInfos: false
          repoToken: ${{ secrets.GITHUB_TOKEN }}
