name: {{ GHA_NAME }}
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run
        shell: pwsh
        run: |
            {{ PS_COMMAND }}
      - name: Commit and Push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore: run {{ GHA_NAME }} workflow'
          commit_user_name: 'GitHub Actions'
