version: "3.3"

services:
  wikmd:
    image: linbreux/wikmd:latest
    container_name: wikmd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /../:/wiki
    ports:
      - 5000:5000
    restart: unless-stopped
